### ISSUE TITLE
Plugins stored in ~/.cache/ ? 

### ISSUE THREAD

**Issue by shanff** [SpaceVim/SpaceVim#2076]
## Expected behavior, english is required
plugins should be stored in "sane" folder

## The reproduce ways from Vim starting (Required!)
Cleanup cached files under ~/.cache/

## Debug info
N/A

## Screenshots
N/A

So, I was performing some cleanups on my $HOME folder recently and cleared out ~/.cache to remove cached and temporary files that applications leave around.  Lo and behold, next time vim fired up, it required a re-download of plugins.  Issue #376 appears to indicate that there is a variable that sets this directory for persistent plugin storage.

`let g:spacevim_plugin_bundle_dir = '~/.cache/vimfiles/'`

This should probably be changed to a program directory rather than ~/.cache as that directory is ideally used for non-essential files. 

https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html

> $XDG_CACHE_HOME defines the base directory relative to which **user specific non-essential data files** should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used.

Any chance this can get changed to something a little more sane, such as in .SpaceVim or .SpaceVim.d as those folders are already associated with SpaceVim rather than having this 3rd related folder being created and used?

**Comment by wsdjeg** [comment]
I do not want to put cache into `~/.SpaceVim` and `~/.SpaceVim.d`. if you want to do this, just change the value of `plugin_bundle_dir` in toml file.

for exmaple:

```toml
[options]
  plugin_bundle_dir = "~/your_cache_dir/"
```

you should not put caches into `~/.SpaceVim` and `~/.SpaceVim.d`, because this two dir are added into vim's runtimepath,  add cache into these two dir will make vim slow.

**Comment by shanff** [comment]
The only thing I have issue with is the plugins.  I would not consider plugins as cache, but as essential program files.  Am I mistaken with that?  I understand that I could change the location myself, I just question the location and why speed would make a difference anywhere unless you have .cache mounted on a different storage medium.  Ultimately it's not going to affect my usage, as I will likely just  change my storage location;  I'm just trying to understand the desire to use a temporary file storage directory for files I would want to hold persistently.   pluging_bundle_dir as a variable name does not indicate it would refer to a "cache" directory.

**Comment by wsdjeg** [comment]
SpaceVim use dein as plugin manager. we can only set the cache dir of dein. and it will create all cache files in that dir. and all plugins will be downloaded in repos/host/author/plugin_name

here host can be github.com or gitlab.com

this structure ia just like golang's package manager.

**Comment by taozhi8833998** [comment]
same problem resolved by setting `plugin_bundle_dir`
