### ISSUE TITLE
some characters in SpaceVim in wsl-terminal not displaying properly

### ISSUE THREAD

**Issue by a1mersnow** [SpaceVim/SpaceVim#2310]
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

![image](https://user-images.githubusercontent.com/13799160/48998732-61e7d200-f18f-11e8-88ba-6ed35b833a5f.png)

it seems caused by font, but I change the font, it doesn't work

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
This is issue with your font config, and I can not fix it, but in SpaceVim v1.0.0, we will not use icons by default.

**Comment by Assimilator** [comment]
![SpaceVim 2021-12-22](https://user-images.githubusercontent.com/4701455/147178089-7f371c90-1879-4e0e-a05c-eb85e7e9b981.png)
[issue_report.md](https://github.com/SpaceVim/SpaceVim/files/7766258/issue_report.md)

Looks like a similar or same issue. Screenshot & report attached.
