### ISSUE TITLE
how to enable relative number on spacevim

### ISSUE THREAD

**Issue by saltfishh** [SpaceVim/SpaceVim#4502]
## Expected behavior, english is required
firstly,thanks for the spacevim team,it's amazing and easy to use for a new vim user.i have use it for a long time.
i wanna to enable the relative number automaticly when using vim,but it sometimes works well,sometimes not and i have tried much to fix it including searching issues & google,but it also doesnt work.

thanks for that

## Output of the `:SPDebugInfo!`

> toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'config#after'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'jellybeans'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/wind/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = ['markdown-preview.nvim', 'vim-smoothie']
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/wind/.cache/vimfiles/'
  plugin_manager = 'dein'
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/wind/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'nvim-lspconfig'
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  -------------------to much conf,i will post it if necessary
  SpaceVim clipboard support check report:
  Checking +clipboard:
      Failed : to support +clipboard, you need has one of following clipboard tools in your $PATH:
               1. xclip
               2. xsel
               3. pbcopy/pbpaste (Mac OS X)
               4. lemonade (for SSH) https://github.com/pocke/lemonade
               5. doitclient (for SSH) http://www.chiark.greenend.org.uk/~sgtatham/doit/
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

  SpaceVim runtime log :
 [ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
 [ SpaceVim ] [22:54:09] [ Info ] Startup with argv: ['/home/wind/.SpaceVim.d/init.toml']
 [ SpaceVim ] [22:54:09] [ Info ] find local conf: /home/wind/.SpaceVim.d/init.toml
 [ SpaceVim ] [22:54:09] [ Info ] loading cached local conf: 
 /home/wind/.cache/SpaceVim/conf/_home_wind__SpaceVim_d_init_toml.json
 [ SpaceVim ] [22:54:09] [ Info ] start to apply config [local]
 [ SpaceVim ] [22:54:09] [ Info ] the func has been added to mode:syntax-checking
 [ SpaceVim ] [22:54:09] [ Info ] the func has been added to mode:spell-checking
 [ SpaceVim ] [22:54:09] [ Info ] the func has been added to mode:paste-mode
 [   rooter ] [22:54:09] [ Info ] Load projects cache from: /home/wind/.cache/SpaceVim/projects.json
 [   rooter ] [22:54:10] [ Info ] project_rooter_patterns option has been change, clear b:rootDir
 [   rooter ] [22:54:10] [ Info ] Start to find root for: /home/wind/.SpaceVim.d/init.toml
 [   rooter ] [22:54:10] [ Info ] buffer name: /home/wind/.SpaceVim.d/init.toml
 [   rooter ] [22:54:10] [ Info ] same as current directory, no need to change.
 [   rooter ] [22:54:10] [ Info ] buffer name: .SpaceVim.d/init.toml
 [   rooter ] [22:54:10] [ Info ] same as current directory, no need to change.
 </details>

## Screenshots

![image](https://user-images.githubusercontent.com/44364154/138118025-a440c1f6-3bbd-4247-b928-05392b4fb717.png)

**Comment by wsdjeg** [comment]
It is:
```
[options]
    relativenumber = true
```

**Comment by saltfishh** [comment]
thanks for ur reply,but is also dont work after add `relativenumber = true` in label `options` 
![image](https://user-images.githubusercontent.com/44364154/138298385-c5124da1-5ab1-4b71-926d-7e0e9d23330f.png)
